#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Image/MNIST/Config
if [ "$OS" == "Windows_NT" ]; then
  CleanDataDir=$(cygpath -aw $DataDir)
else
  CleanDataDir-$DataDir
fi

# cntkrun <CNTK config file name> <additional CNTK args>
imageLayout=cudnn

cntkrun 03_ConvBatchNorm.cntk  "train=[reader=[file=$CleanDataDir/Train.txt]]  test=[reader=[file=$CleanDataDir/Test.txt]]  train=[reader=[randomize=none]]  imageLayout=\"$imageLayout\"" || exit $?

